services:
  otelwithaspirev1:
    image: otelwithaspirev1
    container_name: api
    build:
      context: .
      dockerfile: OtelWithAspireV1/Dockerfile
    ports:
      - 8080:8080
    environment:
#      - OTEL_EXPORTER_OTLP_PROTOCOL=http/protobuf
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4317  #default for grpc # http://prometheus:9090/api/v1/otlp/v1/metrics
    networks:
      - otel
  
  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    container_name: otel-collector
    volumes:
      - ./otel-collector-config.yaml:/etc/otel/config.yaml
    command: [ "--config=/etc/otel/config.yaml" ]
    ports:
      - 4317:4317
    networks:
      - otel

#  aspire.dashboard:
#    image: mcr.microsoft.com/dotnet/nightly/aspire-dashboard:latest
#    container_name: aspire
#    ports:
#      - 18888:18888
#      - 18889:18889
#    networks:
#      - otel
    
  grafana:
    image: grafana/grafana:latest
    ports:
      - "3001:3000"
    depends_on:
       - prometheus
    networks:
      - otel
    volumes:
      - prometheusandgrafana_grafana_storage:/var/lib/grafana
    
  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    networks:
      - otel
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--enable-feature=otlp-write-receiver" # Enable the OTLP write receiver feature
      - "--log.level=debug"
#    depends_on:
#      - otel-collector    
      
      
networks:
  otel:

volumes:
  # influxdb_data:
  prometheusandgrafana_grafana_storage:
    external: true
