services:
  otelwithaspirev1:
    image: otelwithaspirev1
    container_name: api
    build:
      context: .
      dockerfile: OtelWithAspireV1/Dockerfile
    ports:
      - 8080:8080
      - 5244:5244
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://Aspire.dashboard:18889
    networks:
      - otel
  
  
  Aspire.dashboard:
    image: mcr.microsoft.com/dotnet/nightly/aspire-dashboard:latest
    container_name: aspire
    ports:
      - 18888:18888
    networks:
      - otel
      
      
networks:
  otel:
